!: BOLT 3
!: AUTO RESET

C: HELLO {"scheme": "none", "user_agent": "neo4j-java/dev"}
S: SUCCESS {"server": "Neo4j/9.9.9", "connection_id": "bolt-123456789"}
C: RUN "unwind range(1, 15) as n RETURN n" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["n"]}
   RECORD [0]
   RECORD [1]
   RECORD [2]
   RECORD [3]
   RECORD [4]
   RECORD [5]
   RECORD [6]
   RECORD [7]
   RECORD [8]
   RECORD [9]
   SUCCESS {"has_more": true}
C: PULL_ALL
S: RECORD [0]
   RECORD [1]
   RECORD [2]
   RECORD [3]
   RECORD [4]
   SUCCESS {}
